### PR TITLE
Retry deprecation warning fix

### PR DESCRIPTION
**Pull request by ejpenney**
Retries #7 

Sorry about that issue before.

### CODE REVIEW

**Comment by ejpenney** [comment]
Still test issues, I'm gonna take another stab at this. Give me a few minutes...

**Comment by ejpenney** [comment]
So far this adds the breaking change: Increased requirement to 2022.7.0 (and therefore Python>=3.9)

But these dependency updates have introduced other issues, I'm still poking at this.

**Comment by ejpenney** [comment]
Stumped at this point, I'll take another look at it later, but this UnknownHandler error makes no sense.  Looks to me like the domains are properly configured and everything, I'm clearly missing something.

**Comment by ejpenney** [comment]
Upgrading to newer versions of Python/Home Assistant make a lot of these errors go away, but new errors appear.  I suspect a problem with the tests, so much so that I see import_blueprint even removed tests from [upstream](https://github.com/ludeeus/integration_blueprint/commit/15feac505d7b21e6c17e48f918fa04cf0e340a0e).

I've tested this change as-is locally, and all the flows appear to work, but the tests are broken as-is.

**Comment by InTheDaylight14** [comment]
Here are some changes to the tests from another custom component: [https://github.com/alandtse/tesla/pull/892/files](https://github.com/alandtse/tesla/pull/892/files)

This integration is where I was originally inspired to make this custom integration. I'll be honest, a lot of this is outside my wheelhouse. I only dabble in this space and I'm no professional coder.

**Comment by ejpenney** [comment]
I've narrowed it down to a problem with the node the tests are running on here in GitHub, I have an environment running Python 3.8, and all tests pass as the code is now.  It only fails in GitHub.

image

**Comment by ejpenney** [comment]
Thanks, but I'm not seeing anything in that PR that seems particularly helpful.  They've pinned some versions, but pip is more-or-less pulling those same versions here.

I see the reverted PR from the other day also has this UnknownHandler failure also.  It looks like _something_ changed upstream between October and now and is causing this failure.  I have no idea what the issue is, but I suspect something related to a GitHub Action or the ubuntu-latest nodes.  It could be a pip dependency needs to be pinned, but that seems increasingly unlikely the more I poke at it.

I've tried the latest GHA, as well as pinning to python-3.8.19 (the action is picking 3.8.18), but the first makes no difference, and the latter fails (apparently the GitHub node can't find any later versions?!).

I've refactored the change to be extremely simple, based on the changes to upstream, we're not queueing the task anymore at all.  Also updated some HACS metadata for this repository while I was there, because... why not?  Only thing I can say for sure is the test failures on this PR are _not_ related to the changes in this PR.  I tested this again in my development environment and everything appears to work.

I really dislike that I can't get the test working in GitHub, but I'm stumped (again).

**Comment by InTheDaylight14** [comment]
Got it, thanks for investigating. With a year before the functionality being depreciated I'm okay to sit on this PR for a little while. 

I've always found the GitHub test environment to be finicky, given the tests work locally I might be okay with removing the GitHub tests.  I'll keep thinking on it.

**Pull request merged**
